@HOST = http://localhost/api/research
@TOKEN = Bearer admintoken


GET {{HOST}}.all
Authorization: {{TOKEN}}

###
POST {{HOST}}.save
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "id": 10,
    "private_name": null,
    "public_name": "my name",
    "description": "how to do this",
    "blocks": []
}
###
POST {{HOST}}.remove
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "id":1
}
###
GET {{HOST}}.get
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "slug": "PnfW2GCnWu"
}
###
POST {{HOST}}.unpublish
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "slug": "PnfW2GCnWu"
}
###
POST {{HOST}}.publish
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "id": 13
}
###
GET {{HOST}}.respondent.get?slug=PnfW2GCnWu